pipeline:
  name: C4 Modelleur Agent
  description: Genereert C4 model diagrammen
  
  trigger:
    type: manual
    inputs:
      source_docs:
        description: Path to source documents for C4 model
        required: true
        type: string

  environment:
    runner: ubuntu-latest
    python-version: "3.11"
  
  steps:
    - id: checkout
      action: checkout
    
    - id: setup-python
      action: setup-python
      with:
        version: ${{ environment.python-version }}
    
    - id: install-deps
      action: run
      command: pip install -r requirements.txt
    
    - id: run-agent
      action: run
      command: |
        python agent-componenten/runners/u.c4-modelleur.py --input ${{ inputs.source_docs }}
    
    - id: upload-artifacts
      action: upload-artifact
      with:
        name: c4-model-diagrams
        path: output/c4-diagrams/
  
  notifications:
    on-failure:
      slack:
        channel: agent-alerts
        message: Agent u.c4-modelleur failed
