# This file configures the agent aliases that can be used in this repository.
# Each key is an agent alias that can be invoked with @workspace /<alias>
# The value is a short description of what the agent does.

agents:
  0.agent-cap-moeder:
    description: "Moeder-agent voor het beheren van agent-capabilities workspace."
  
